config/routes.rb
NeubauerPhoto::Application.routes.draw do
  root :to => 'pages#home'

  match '/about'   => "pages#about"
  match '/gallery' => "pages#gallery"
  match '/home'    => "pages#home"
  match '/contact' => "pages#contact"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_filter :get_photosets


  protect_from_forgery

  private

  def get_photosets
    flickr = Flickr.new('05ad56341ed719ab0c1d65aca564c863')
    @photosets = flickr.users('eneubauer').photosets.sort {|x,y| x.title <=> y.title }
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def gallery
  end

  def about
  end

  def contact
  end

  def home
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:name => "language", :content => "en"}
    %meta{:name=>"keywords", :content=>"photographer, Columbus Ohio, Pickerington, weddings, family portraits, high school seniors, on location, Erin Neubauer, portraits, portraiture, Columbus Ohio Wedding Photographer"}
    %meta{:name=>"keyword phrase", :content=>"Erin Neubauer Photography : Central Ohio, Columbus, Ohio, Wedding Photographers, Family Photographers, Senior Portrait Photography, wedding coverage, wedding photography, bridal photography, family portraits, child portraits, Photography, columbus ohio"}
    %meta{:name=>"description", :content=> "Affordable, creative photography services for portraits, events, weddings. Contact Erin Neubauer xxx.xxx.xxxx."}
    %meta{:name=>"author", :content=>"Protected Method LLC, Columbus, OH: www.protectedmethod.com"}

    %title Erin Neubauer Photography
    = stylesheet_link_tag "application"
    = stylesheet_link_tag "vendor"
    = stylesheet_link_tag "galleria.classic.css" #has to be included manually otherwise galleria can't find it

    = javascript_include_tag "application"

  %body
    #container
      = yield

app/views/pages/about.html.haml
=render "shared/sidebar", :gallery => false

#about
  %p
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin massa lectus, commodo non porta id, viverra id tortor. Nulla facilisi. Donec sed sagittis enim. Pellentesque gravida risus sed ligula pellentesque quis blandit risus aliquam. Donec nec nisi ut metus mollis lacinia. Nam neque risus, faucibus eget vehicula eget, facilisis vitae dolor. Ut tincidunt porttitor justo, sed egestas diam dictum quis.
  %p
    Duis eget orci orci. Proin eu dapibus erat. Integer mattis tempus dolor, eu sagittis elit pharetra nec. Vivamus molestie, justo tempor tristique pharetra, dui dolor vehicula diam, id vestibulum metus nisl ac mauris. Donec eu lorem lorem, et ornare felis. Vestibulum suscipit adipiscing ultricies. Nunc eu massa lorem, id tempus tellus. Vestibulum feugiat scelerisque eros, eget pharetra nunc tempus at. Duis lacinia est in risus viverra vitae suscipit enim lobortis. Mauris suscipit pulvinar urna vitae accumsan. Phasellus auctor mauris eget dolor vulputate vitae malesuada orci imperdiet.
  %p
    Nunc ut blandit dolor. Duis sed neque turpis, non sollicitudin augue. Curabitur sed odio dolor. Phasellus at odio nec nibh posuere varius. Integer nec augue consequat urna fringilla consectetur. Cras tristique elit at quam gravida convallis. Donec euismod magna ut ipsum malesuada ut mattis magna commodo. Donec ac libero nulla. Donec nec massa sed magna aliquam eleifend tincidunt a velit. Ut auctor lacinia velit, vitae tristique mauris eleifend ac.
  %p
    Morbi fringilla nibh vel lacus tristique sollicitudin. Ut mollis, felis quis egestas posuere, felis tortor volutpat justo, a fermentum leo purus vitae eros. Nunc cursus arcu lectus, in sodales nibh. Duis feugiat condimentum ornare. Vestibulum ut mi libero, in vestibulum massa. Maecenas at viverra dolor. Sed commodo, sem at ultrices aliquam, metus diam interdum odio, vel pellentesque diam ante eget metus. Nullam tincidunt lectus quis urna ultrices in bibendum mi fringilla. Nulla in nisl nec nisl auctor interdum id in enim. Vivamus fringilla augue eget quam consectetur non ullamcorper urna dapibus. Maecenas lacus tellus, pretium id varius condimentum, pulvinar nec dui. Nullam at dignissim sem. Nam suscipit elit mi, id pellentesque massa. Vivamus vitae diam risus, eu consequat neque. Quisque consectetur, magna in laoreet molestie, orci est fringilla lacus, eget bibendum sem arcu eget enim. Curabitur ante tellus, lobortis consectetur ornare eget, porttitor vel urna.
  %p
    Etiam lacus sem, hendrerit hendrerit cursus molestie, sollicitudin eget velit. Nulla arcu quam, malesuada sed mollis ut, accumsan at ipsum. Sed est felis, sollicitudin eu egestas hendrerit, lobortis at elit. Suspendisse auctor pellentesque ipsum, non interdum metus elementum et. Nunc et mauris vel libero molestie adipiscing ac at ante. Sed blandit nisl quis nibh mattis eget gravida risus aliquam. Integer ullamcorper hendrerit ipsum commodo vestibulum. Duis eu gravida odio. Pellentesque in turpis sapien. Maecenas rhoncus arcu sit amet purus aliquam tristique. Ut ut turpis at risus ullamcorper egestas a non neque. Mauris eget nulla nec arcu condimentum porta ac sed lorem. Praesent eu ligula arcu. Etiam id felis quis arcu tincidunt porttitor id a risus. Praesent magna velit, congue venenatis tempus non, varius at leo.

app/views/pages/contact.html.haml
=render "shared/sidebar", :gallery => false

#contact

app/views/pages/gallery.html.haml
=render "shared/sidebar", :gallery => true

#gallery_wrapper
  #gallery_info
    %span.gallery-name
      KIDS
    %span.photo-count
      1 of 4
    %span.photo-nav
      %a.prev ◀
      &nbsp;
      %a.next ▶

  #gallery

:javascript

  $(function(){

    // Initialize Galleria
    $('#gallery').galleria({
      lightbox: true,
      showInfo: false,
      showImagenav: false,
      thumbnails: false,
      showCounter: false
    });

    $("a.photoset-link").click(function(e){
      e.preventDefault();
      loadGallery( $(this).attr('href'), $(this).text() );
    });

    $("a.next").click(function(e){
      e.preventDefault();
      var gallery = Galleria.get(0);
      gallery.next();
    });

    $("a.prev").click(function(e){
      e.preventDefault();
      var gallery = Galleria.get(0);
      gallery.prev();
    });

    Galleria.get(0).bind("image", function(e){
      var left = $(e.imageTarget).css("left").replace('px', '');
      left = left - ( Math.min(left, 15)) + "px";

      $(e.imageTarget).css("left", left);

      var gallery = Galleria.get(0);
      $('.photo-count').text((gallery.getIndex() + 1) + " of " + gallery.getDataLength() )
    });

    var initialGalleryId = '#{params[:id]}' || $("a.photoset-link:first").attr("href");
    $("a.photoset-link[href='" + initialGalleryId + "']").click();

    function loadGallery(setId, setName){
      var setGallery = function(data) { updateGallery(data, setName); };
      var flickr = new Galleria.Flickr();
      flickr.setOptions({sort: 'interestingness-desc'});

      if (setId && setId.length > 0)
        flickr.set(setId, setGallery)
      else
        flickr.user('eneubauer', setGallery)
    }

    function updateGallery(data, setName){
      var gallery = Galleria.get(0);
      gallery.load(data)
      $('.gallery-name').text(setName.toLowerCase().capitalize())
    }

  });

app/views/pages/home.html.haml
.center-align
  %h2.banner-horizontal
    =link_to "Erin Neubauer", home_path
    %strong
      =link_to "Photography", home_path

  %h1.first Hello and nice to meet you!
  %h1 I'm Erin Neubauer,
  %h1 a freelance photographer.

  %ul#horizontal_nav
    - @photosets.each do |p|
      %li
        = link_to p.title.upcase, gallery_path(:id => p.id)

    %li= link_to "ABOUT", about_path
    %li= link_to "CONTACT", contact_path

app/views/shared/_sidebar.html.haml
#sidebar
  .banner-vertical
    %h2.first
      =link_to "Erin Neubauer", home_path

    %h2.last
      %strong
        =link_to "Photography", home_path

  %ul#vertical_nav
    - @photosets.each do |p|
      %li
        -if gallery
          = link_to p.title.upcase, p.id, :class => 'photoset-link'

        -else
          = link_to p.title.upcase, gallery_path(:id => p.id)

    %li= link_to "ABOUT", about_path
    %li= link_to "CONTACT", contact_path